### PR TITLE
[fill-stroke] Rename 'stupid' in 'fallback'

### PR DESCRIPTION
**Pull request by Zefling**

### CODE REVIEW

**Comment by AmeliaBR** [comment]
Marked as non substantive for IPR from ash-nazg.

**Comment by BigBadaboom** [comment]
There are also references to `stupid` in `stroke-linejoin` still

**Comment by FremyCompany** [comment]
@AmeliaBR Are there any implementation of this? Otherwise I can just go ahead and merge.

**Comment by AmeliaBR** [comment]
@FremyCompany  There are definitely no implementations of a `stupid` value. That was just a placeholder in the spec because @TabAtkins & @fantasai want to replace the SVG 1 definition of `miter`.

@BigBadaboom There aren't any other uses of `stupid` as a keyword in the [source file](https://github.com/w3c/fxtf-drafts/blob/feddbc8b701e083d10708959f65b4824949235fb/fill-stroke/Overview.bs). The other places in the generated file are created automatically.

**Comment by Zefling** [comment]
@AmeliaBR It's a placeholder, but currently the draft says `stupid` and `fallback` for the same value.
I have not change this description:  “It's a stupid value, useful only because we didn't have the clip-at-miterlimit behavior in SVG1.”  It's just for a better understanding.

**Comment by FremyCompany** [comment]
I merged it, no reason to risk someone implementing `stupid` as a keyword for SVG :) Can always be rebikesheded later if needed

**Pull request merged**
