### PR TITLE
[geometry-1] Use new WebIDL constructor definition

### PR DESCRIPTION
**Pull request by dirkschulze**

### CODE REVIEW

**Comment by dirkschulze** [comment]
Please do not land yet as the change breaks links within the spec. Needs fixes in Bikeshed first.

**Comment by dirkschulze** [comment]
Fix for #367

**Comment by tabatkins** [comment]
Bikeshed fix is in, let me know if there are any problems.

**Comment by dirkschulze** [comment]
@tabatkins Seems to work perfectly. Thanks!

**Pull request merged**
