### PR TITLE
[geometry-1] Define minimum and maximum as preferring NaN

### LINKED ISSUE #222: [geometry] DOMRect: use of unrestricted doubles - min(x, NaN)
https://drafts.fxtf.org/geometry/#DOMQuad

> Let left be the minimum of point 1’s x coordinate, point 2’s x coordinate, point 3’s x coordinate and point 4’s x coordinate\.

See http://www.w3.org/mid/CAGN7qDCS4U=aa2bVec1OCUVSMECAgUDwZT5fSj8HS1Ue6AJozw@mail.gmail.com from @smfr 
cc @cabanier

### PR DESCRIPTION
**Pull request by TimothyGu**
This follows the rough consensus reached in #222, as well as what WebKit
implements today.

Fixes #222.

----

Tests: ...

I'm be happy to implement this in Chrome. If this is deemed acceptable, I could just write the WPTs as part of the Chromium change.

### CODE REVIEW

**Comment by tabatkins** [comment]
@svgeesus Heya Chris, Timothy is an undergrad, can you hook them up with a non-participant licensing agreement?

(Or maybe @astearns or @atanassov know how to do this.)

**Comment by astearns** [comment]
It's a team-only thing. @xfq should be able to kick it off, too.

**Comment by xfq** [comment]
Done.

**Comment by TimothyGu** [comment]
cc @bzbarsky @zcorpan

**Comment by bzbarsky** [comment]
@TimothyGu fwiw, I am not actively working on web platform stuff.  If you were just aiming to cc someone from Mozilla, probably someone else is a good idea...

**Comment by zcorpan** [comment]
This seems good to me. Tests should include at least this case https://github.com/w3c/fxtf-drafts/issues/222#issuecomment-382143487

Thanks!

**Comment by TimothyGu** [comment]
@emilio Would you happen to have any thoughts on this?

**Comment by emilio** [comment]
This looks pretty reasonable to me off-hand.

@saschanaz has done some geometry stuff in the past and may have stronger opinions.

**Comment by saschanaz** [comment]
LGTM too.

**Comment by TimothyGu** [comment]
@chrishtr Yes. I'm adding one as a part of https://chromium-review.googlesource.com/c/chromium/src/+/2129889, which will be sent out for review as soon as dry-running finishes.

**Comment by chrishtr** [comment]
Great!

**Comment by TimothyGu** [comment]
@zcorpan The tests are in https://github.com/web-platform-tests/wpt/pull/22585 / https://chromium-review.googlesource.com/c/chromium/src/+/2129889. Feel free to review it anywhere.

**Pull request merged**
