### PR TITLE
[geometry] Replace serializers with "[Default] toJSON()".

### LINKED ISSUE #200: [geometry] WebIDL serializer has been deprecated in favor of toJSON operation
Hi!

We recently [deprecated WebIDL serializers][0]. You can now directly specify [toJSON operations][1] instead, which you previously weren't allowed to do.

To deal with common cases, we added a new [\[Default\] extended attribute][2] which triggers the [default toJSON operation][3] that behaves similarly to how `serializers={attributes}` or `serializers={attributes, inherit}` used to. That is, it serializes all attributes that are of a [JSON type][4] into a vanilla JSON object.

It seems the following interfaces in this spec are impacted by this change:

- [ ] [`DOMPointReadOnly`](https://drafts.fxtf.org/geometry/#dompointreadonly)
- [ ] [`DOMRectReadOnly`](https://drafts.fxtf.org/geometry/#domrectreadonly)
- [ ] [`DOMQuad`](https://drafts.fxtf.org/geometry/#domquad)
- [ ] [`DOMMatrixReadOnly`](https://drafts.fxtf.org/geometry/#dommatrixreadonly)

All of these seem good candidate for the [default toJSON operation][3], so the below should be all you need:

```webidl
 // Extended attributes
interface DOMPointReadOnly {
    [NewObject] static DOMPointReadOnly fromPoint(optional DOMPointInit other);

    readonly attribute unrestricted double x;
    // Etc...

    DOMPoint matrixTransform(optional DOMMatrixInit matrix);

    [Default] object toJSON();
};

// Extended attributes
interface DOMRectReadOnly {
    [NewObject] static DOMRectReadOnly fromRect(optional DOMRectInit other);

    readonly attribute unrestricted double x;
    // Etc...

    [Default] object toJSON();
};

// Extended attributes
interface DOMQuad {
    [NewObject] static DOMQuad fromRect(optional DOMRectInit other);
    // Etc...

    [SameObject] readonly attribute DOMPoint p1;
    // Etc...

    [NewObject] DOMRect getBounds();

    [Default] object toJSON();
};

// Extended attributes
interface DOMMatrixReadOnly {
    [NewObject] static DOMMatrixReadOnly fromMatrix(optional DOMMatrixInit other);
    // Etc...
    
    [Exposed=Window] stringifier;
    
    [Default] object toJSON();
};
```
I'm sorry for the inconvenience this causes, but our hope is that this ultimately makes things a lot simpler and clearer for everybody.

Please feel free to reach out if you have any questions.

Thanks!

[0]: https://github.com/heycam/webidl/commit/a505f33
[1]: https://heycam.github.io/webidl/#idl-tojson-operation
[2]: https://heycam.github.io/webidl/#Default
[3]: https://heycam.github.io/webidl/#es-default-tojson
[4]: https://heycam.github.io/webidl/#dfn-json-types

### PR DESCRIPTION
**Pull request by romandev**
Match latest WebIDL spec[1]. This fixes #200.

[1] https://heycam.github.io/webidl/#Default

### CODE REVIEW

**Comment by romandev** [comment]
@zcorpan PTAL.

**Comment by zcorpan** [comment]
From what I understand of WebIDL, it is already required to run the default toJSON operation from the given IDL, so it's wrong to require it again in prose here. Correct @tobie @domenic ?

**Comment by tobie** [comment]
Well, the prose is redundant, yes.

**Comment by romandev** [comment]
I removed the prose.

**Comment by zcorpan** [comment]
Should update https://github.com/w3c/web-platform-tests/blob/master/interfaces/geometry.idl to match this. @romandev are you interested in doing a PR for that also?

**Comment by romandev** [comment]
Yes, I will. Thanks.

**Comment by romandev** [comment]
FYI, I uploaded a test: https://github.com/w3c/web-platform-tests/pull/7253

**Comment by zcorpan** [comment]
For commit message, this fixes https://github.com/w3c/fxtf-drafts/issues/200

**Comment by zcorpan** [comment]
Thank you!

**Pull request merged**
